FROM php:8.4.1-fpm

# Set working directory
WORKDIR /var/www

RUN apt-get update && apt-get install -y \
    git zip unzip curl \
    libpng-dev libzip-dev zlib1g-dev

# Install PHP extensions
RUN docker-php-ext-install pdo pdo_mysql gd \
    && docker-php-ext-configure zip \
    && docker-php-ext-install zip

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

COPY . .

RUN composer install --no-scripts --no-interaction

CMD ["php-fpm"]
